spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: shynode-egg
      # 自动将字段转换为驼峰标识存储到mongo中.
      field-naming-strategy:  org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      username: root
